import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Building2, CheckCircle2, MapPin, ShieldCheck, Users } from "lucide-react";

const teachers = [["Prof. Ana Matias", "Física · 10.º A", "32 alunos"], ["Prof. Joel Manuel", "Matemática · 9.º B", "29 alunos"], ["Prof. Lurdes Paulo", "Biologia · 11.º C", "26 alunos"]];

export function SchoolDashboard() {
  return <main className="school-shell">
    <header className="school-nav"><Link href="/" className="landing-brand"><Image src="/brand/morph-lockup.jpg" alt="morph" width={176} height={50} priority /></Link><div className="school-nav-title"><span>PAINEL DA ESCOLA</span><strong>Colégio Horizonte</strong></div><Link href="/teacher" className="school-teacher-link">Abrir studio do professor <ArrowRight size={15} /></Link></header>
    <section className="school-hero"><div><p className="landing-eyebrow"><span /> VISÃO DA SCHOOL BUBBLE</p><h1>O contexto certo<br />para cada aula.</h1><p>Este painel demonstra como a escola organiza espaço, pessoas e permissões pedagógicas.</p></div><div className="school-health"><span className="live-dot" /> <strong>School Bubble activa</strong><small>Campus Horizonte · 12 dispositivos elegíveis</small></div></section>
    <section className="school-metrics" aria-label="Indicadores da escola"><article><Building2 size={21} /><span><strong>01</strong><small>campus configurado</small></span></article><article><Users size={21} /><span><strong>14</strong><small>professores activos</small></span></article><article><CheckCircle2 size={21} /><span><strong>286</strong><small>alunos associados</small></span></article><article><ShieldCheck size={21} /><span><strong>04</strong><small>aulas em curso</small></span></article></section>
    <section className="school-grid"><article className="school-card school-bubble-card"><div className="school-card-header"><div><p>CONTEXTO</p><h2>School Bubble</h2></div><span className="school-tag">CONFIGURADA</span></div><div className="campus-map"><div className="map-ring map-ring-a" /><div className="map-ring map-ring-b" /><div className="map-campus"><Building2 size={30} /><strong>Campus Horizonte</strong><small>Raio pedagógico: 180 m</small></div><div className="map-pin pin-a"><MapPin size={18} /></div><div className="map-pin pin-b"><MapPin size={18} /></div></div><p className="school-card-note">A Bubble define o contexto de aplicação da política. Não é um mecanismo de monitorização contínua.</p></article><article className="school-card school-lesson-card"><div className="school-card-header"><div><p>AGORA</p><h2>Aulas em curso</h2></div><span className="school-tag blue-tag">04 ACTIVAS</span></div><div className="current-lesson"><span className="live-dot" /><div><strong>Movimento acelerado</strong><small>Prof. Ana Matias · 10.º A</small></div><b>MEDIR</b></div><div className="current-lesson muted-lesson"><span /><div><strong>Equações do 2.º grau</strong><small>Prof. Joel Manuel · 9.º B</small></div><b>COMPREENDER</b></div><Link href="/teacher" className="school-card-link">Conduzir uma aula <ArrowRight size={16} /></Link></article></section>
    <section className="school-card school-people-card"><div className="school-card-header"><div><p>COMUNIDADE</p><h2>Professores e alunos associados</h2></div><span className="school-tag">DEMO SEM LOGIN</span></div><div className="teacher-list">{teachers.map(([name, className, students]) => <div className="teacher-row" key={name}><div className="teacher-avatar">{name.split(" ").slice(1, 3).map((part) => part[0]).join("")}</div><div><strong>{name}</strong><small>{className}</small></div><span>{students}</span><CheckCircle2 size={18} /></div>)}</div></section>
    <footer className="school-footer"><Link href="/">← Voltar à landing</Link><span>Protótipo de gestão escolar · autenticação será adicionada após validação da ideia.</span></footer>
  </main>;
}
